"""サイト内で使うアプリ台帳。ページ生成スクリプトはすべてここを唯一の情報源にする。

App Store Connect の状態が変わったら、ここと各HTMLの状態行を更新する。
"""

# state: "live"（公開中） / "review"（審査中） / "prepare"（申請準備中）
APPS = [
    dict(slug="shizukatl", name="しずかTL for X", appid="6796696394", state="live",
         price="買い切り 120円", os="iOS 17+",
         tagline="タイムラインを、静かに、順番どおりに。",
         short="Safari で X を時系列・静かな画面で読む拡張機能。効いているかを診断できる。",
         topic="画面まわり・気晴らし"),
    dict(slug="sukemaru", name="透けマル", appid="6796656589", state="live",
         price="買い切り 120円", os="iOS 17+",
         tagline="透過できたか、数値で分かる。",
         short="背景を消して透過PNGに。書き出したファイルを読み戻してアルファを実測する。",
         topic="画面まわり・気晴らし"),
    dict(slug="kaeseru", name="カエセル", appid="6796657244", state="live",
         price="買い切り 120円", os="iOS 17+",
         tagline="グラフではなく、円の差額で答える。",
         short="住宅ローンの計算。金利上昇と繰上返済の損得を金額で出す。",
         topic="仕事の道具"),
    dict(slug="sagaseru", name="サガセル録音", appid="6796545639", state="live",
         price="買い切り 120円", os="iOS 17+",
         tagline="録音を、話した言葉で探す。",
         short="文字起こしの1文をタップすると音声がその瞬間まで飛ぶボイスメモ。",
         topic="仕事の道具"),
    dict(slug="hitoriinvoice", name="ひとり請求書", appid="6796195340", state="live",
         price="買い切り 120円", os="iOS 17+",
         tagline="明細の件数で、行き止まらない。",
         short="見積・納品・請求・領収を同じ明細から1タップ。インボイス対応。",
         topic="仕事の道具"),
    dict(slug="tsuzukutodo", name="つづくToDo", appid="6796174701", state="live",
         price="買い切り 120円", os="iOS 17+",
         tagline="習慣もToDoも、ひとつの画面で。",
         short="上限のないタスク、取り消せる記録、あとから付けられる日。",
         topic="毎日の記録"),
    dict(slug="shimekiri", name="シメキリ逆算", appid="6796252958", state="live",
         price="買い切り 120円", os="iOS 17+",
         tagline="今日やる分を、締切から逆算する。",
         short="間に合わないときは、延ばす日数・増やす分数・削る量を数字で出す。",
         topic="毎日の記録"),
    dict(slug="kinshuwatch", name="禁酒ウォッチ", appid="6795822272", state="live",
         price="買い切り 100円", os="iOS 17+",
         tagline="飲んでいない時間が、積み上がる。",
         short="本数・金額・カロリーに換算。飲んでも記録は消えない。",
         topic="毎日の記録"),
    dict(slug="kigyouojisan", name="起業おじさん", appid="6795361615", state="live",
         price="無料", os="iOS 17+",
         tagline="起業の悩みを、話せる相手。",
         short="まず聞いて、今週できる一歩を1つか2つだけ示す相談アプリ。",
         topic="仕事の道具"),
    dict(slug="othello", name="ぱすてるオセロ", appid="6793739141", state="live",
         price="無料", os="iOS 16+",
         tagline="Lv1は必ず勝てる。Lv10は全力。",
         short="レベル1〜10のCPUと対戦。オフラインで遊べる。",
         topic="画面まわり・気晴らし"),
    dict(slug="dandorirecipe", name="だんどりレシピ", appid="6798937712", state="prepare",
         price="買い切り 120円", os="iOS 17+",
         tagline="つくれる状態まで、持っていく。",
         short="人数換算・売り場順の買い物リスト・同時タイマー。写真からレシピを取り込める。",
         topic="毎日の記録"),
    dict(slug="hanalog", name="ハナログ", appid="6798935243", state="prepare",
         price="無料（120円の買い切りで無制限）", os="iOS 17+",
         tagline="話すだけで、日記になる。",
         short="音声を端末内で文字起こしし、読める形に整える音声日記。",
         topic="毎日の記録"),
    dict(slug="oboerukakeibo", name="オボエル家計簿", appid="6798934706", state="prepare",
         price="買い切り 120円", os="iOS 17+",
         tagline="撮ったその場で入る。2回目からは店を覚える。",
         short="レシートを端末内で読み取り、待たずに記録。画像は保存も送信もしない。",
         topic="仕事の道具"),
    dict(slug="magedori", name="マゲドリ", appid="6798952257", state="live",
         price="買い切り 120円", os="iOS 17+",
         tagline="自分のベンダーの癖を、覚えさせる。",
         short="日本のJIS電線管専用の曲げ寸法計算。試し曲げ1回で実効芯半径を逆算。",
         topic="仕事の道具"),
    dict(slug="negotouranai", name="ねごと占い", appid="6798951966", state="live",
         price="買い切り 120円", os="iOS 17+",
         tagline="寝言を録って、読み解く。",
         short="就寝中の寝言を自動録音し、端末内で文字起こしして夢占い風に読み解く。",
         topic="画面まわり・気晴らし"),
    dict(slug="repodasu", name="レポダス", appid="6799562833", state="live",
         price="買い切り 120円", os="iOS 17+",
         tagline="1件に、写真は何枚でも。",
         short="現場の指摘を写真何枚でもまとめ、その場でA4のPDF報告書にする。通信なし。",
         topic="仕事の道具"),
    dict(slug="naraseru", name="ナラセル", appid="6799580268", state="prepare",
         price="買い切り 120円", os="iOS 17+",
         tagline="長押しで録って、離すと楽器。",
         short="身のまわりの音をその場でパッドに載せるサンプラー。保存操作なし、書き出しはWAV。",
         topic="画面まわり・気晴らし"),
    dict(slug="musuberu", name="ムスベル", appid="6799579385", state="live",
         price="買い切り 120円", os="iOS 17+",
         tagline="名前を知らなくても、用途から引ける。",
         short="ロープの結び方を3Dで。動かす端を色分けし、締め込みまで見せる結び方辞典。",
         topic="仕事の道具"),
    dict(slug="kagikake", name="カギカケ", appid="6799562522", state="live",
         price="買い切り 120円", os="iOS 17+",
         tagline="教えても、本物は出てこない。",
         short="写真・動画・ファイルを端末内で暗号化する金庫。ダミーのパスコードで別の金庫が開く。",
         topic="仕事の道具"),
]

BY_SLUG = {a["slug"]: a for a in APPS}


def store_url(appid, ct):
    """App Store のURL。ct はキャンペーントークンで、App Store Connect の
    App Analytics → 獲得 → キャンペーン に流入元として表示される（無料）。"""
    return f"https://apps.apple.com/jp/app/id{appid}?ct={ct}&mt=8"
